export const START_FETCHING_KEGIATANS =
  "redux/WorkOrder/START_FETCHING_KEGIATANS";
export const SUCCESS_FETCHING_KEGIATANS =
  "redux/WorkOrder/SUCCESS_FETCHING_KEGIATANS";
export const ERROR_FETCHING_KEGIATANS =
  "redux/WorkOrder/ERROR_FETCHING_KEGIATANS";
