export const START_FETCHING_LISTS_PROYEK =
  "redux/lists/START_FETCHING_LISTS_PROYEK";
export const SUCCESS_FETCHING_LISTS_PROYEK =
  "redux/lists/SUCCESS_FETCHING_LISTS_PROYEK";
export const ERROR_FETCHING_LISTS_PROYEK =
  "redux/lists/ERROR_FETCHING_LISTS_PROYEK";